- name: add application user
  ansible.builtin.user:
    name:roboshop

- name: Remove old app directory
  ansible.builtin.file:
    path: /app
    state: absent

- name: create app directory
  ansible.builtin.file:
    path: /app
    state: directory
- name: Download and extract app content
  ansible.builtin.unarchive:
  src: https://roboshop-artifacts.s3.amazonaws.com/{{ componeny }}.zip
  dest: /app
  remote_src: yes

